base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerPage, name="register"),
    

    #path('', views.home, name="home"),
   
    path('profile/<str:username>/', views.userProfile, name="user-profile"),
    path('update-user/', views.updateUser, name="update-user"),

    path('', views.rooms, name="rooms"),
    path('room/<str:pk>/', views.room, name="room"),
    path('create-room/', views.createRoom, name="create-room"),
    path('update-room/<str:pk>/', views.updateRoom, name="update-room"),
    path('delete-room/<str:pk>/', views.deleteRoom, name="delete-room"),
    path('delete-message/<str:pk>/', views.deleteMessage, name="delete-message"),

    path('topics/', views.topicsPage, name="topics"),
    path('activity/', views.activityPage, name="activity"),
]

note/urls.py
from django.urls import path
from .import views


urlpatterns = [

    path('',views.note, name='note'),
    path('upload_notes/', views.upload_notes, name="upload_notes"),
    path('my_notes/', views.my_notes, name="my_notes"),
    path('contact/', views.contact, name="contact"),
    path('delete_mynotes/<int:pid>',views.delete_mynotes,name="delete_mynotes"),
    path('allsubjects/', views.AllSubjectPage, name="subjects"),
   path('notes/<int:note_id>/download/', views.download_note, name='download_note'),
]

shareMeNote/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rooms/', include('base.urls')),
     path('', include('note.urls')),
    path('blog/', include('blog.urls')),
    path("products/", include("products.urls")),
    path('social-auth/', include('social_django.urls', namespace='social')), # <--
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

note/models.py
from django.db import models
from base.models import User
# Create your models here.


BRANCH_CHOICES = ( 
    ("CSE", "CSE"), 
    ("EEE", "EEE"), 
    ("CIVIL", "CIVIL"), 
    ("MECHANICAL", "MECHANICAL"), 
    ("IT", "IT"), 
    ("NETWORKING", "NETWORKING"), 
    ("ECE", "ECE"), 
    ("OTHER", "OTHER"), 
) 

FILETYPE_CHOICES = (
    ("pdf", "PDF"), 
    ("doc", "DOC/DOCX"), 
    ("CIVIL", "CIVIL"), 
    ("ppt", "PPT/WORD"), 
    ("zip", "ZIP"), 
    ("image", "IMAGE"),  
    ("OTHER", "OTHER"), 
)

class AllSubject(models.Model):
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name

class Notes(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    uploadingdate = models.DateField(auto_now_add = True)
    branch = models.CharField(max_length=30,  choices = BRANCH_CHOICES, default = 'CSE')
    subject = models.ForeignKey(AllSubject, on_delete=models.SET_NULL, blank=True, null=True)
    notesfile = models.FileField(null=True,upload_to='note')
    filetype = models.CharField(max_length=30, choices = FILETYPE_CHOICES, default = 'pdf')
    description = models.CharField(max_length=200, null=True)
    status = models.BooleanField('Approved', default = False)
    downloads = models.IntegerField(default=0)  # Add this field
    update = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    

    class Meta:
        ordering = ['-update', '-created']

    def __str__(self):
        return str(self.subject)

class Contact(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=200,default="")
    notesfile = models.FileField(null=True,upload_to='contacy')
    description = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=12)

note/forms.py
from django.forms import ModelForm


from .models import Notes,Contact


class NoteForm(ModelForm):
    class Meta:
        model = Notes
        fields = ['branch', 'notesfile', 'filetype' ,'description']
class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['notesfile','name','description','phone']

note/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from base.models import User
from blog.models import Post
from .models import Notes,AllSubject,Contact
from .forms import NoteForm,ContactForm
from django.db.models import Q
from django.core.paginator import Paginator
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
# note shareing views here started
# |
        # Q(branch__icontains=q) |
        # Q(description__icontains=q)
def note(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    users = User.objects.all()

    posts = Post.objects.all()[:5]
    # pagination 
    Notedata = Notes.objects.filter(status=True and
        Q(subject__name__icontains=q) 
    )
    Note_count = Notes.objects.filter(status=True).count()
    subjects = AllSubject.objects.all()[0:5]
    page = Paginator(Notedata, 5)
    page_number = request.GET.get('page', 1)
    NoteDataFinal = page.get_page(page_number)
    totalpage = NoteDataFinal.paginator.num_pages
    context = {'data':NoteDataFinal,'subjects':subjects, 'posts':posts, 'note_count':Note_count, 'users':users, 'lastpage':totalpage,'totalpagelist':[n+1 for n in range (totalpage)],'page':page_number}
    return render(request,'note/note.html',context)

def download_note(request, note_id):
    note = get_object_or_404(Notes, id=note_id)
    note.downloads += 1
    note.save()
    context = {"note":note}
    return render(request, "note/sucess.html", context)

def update_download_count(request):
    if request.method == 'POST':
        note_id = request.POST.get('note_id')
        if note_id is not None:
            note = get_object_or_404(Notes, pk=note_id)
            note.downloads += 1
            note.save()
            return JsonResponse({'success': True})
    return JsonResponse({'success': False}, status=400)

@login_required(login_url='login')
def upload_notes(request):
    error=""
    form = NoteForm()
    subjects = AllSubject.objects.all()
    if request.method == 'POST':
        form = NoteForm(request.POST, request.FILES)
        subject_name = request.POST.get('subject')
        subject, created = AllSubject.objects.get_or_create(name = subject_name)
        if request.method=='POST':
            notes = form.save(commit=False)
            notes.user = request.user
            notes.branch = request.POST.get('branch')
            notes.subject = subject
            notes.notesfile = request.FILES.get('notesfile')
            notes.filetype = request.POST.get('filetype')
            notes.description = request.POST.get('description')
            notes.save()
            messages.info(request, 'Note createrd successfully')
            return redirect('my_notes')
        else:
            messages.error(request, 'Note not createrd')
    context = {'form':form, 'subjects':subjects}
    return render(request,'note/upload_note.html',context)

def my_notes(request):
    if not request.user.is_authenticated:
        return redirect('login')
    user = User.objects.get(id=request.user.id)
    notes = Notes.objects.filter(user=user)
    #print(notes)

    context = {'notes':notes}
    return render(request, 'note/my_notes.html',context)




def delete_mynotes(request,pid):
    if not request.user.is_authenticated:
        return redirect('login')
    
    notes = Notes.objects.get(id=pid)
    notes.delete()
    return redirect('my_notes')


def AllSubjectPage(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    subjects = AllSubject.objects.filter(name__icontains=q)
    return render(request, 'note/allsubjects.html', {'subjects': subjects})

def contact(request):
    error=""
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES)
        if request.method=='POST':
            contact = form.save(commit=False)
            contact.user = request.user
            contact.notesfile = request.FILES.get('notesfile')
            contact.description = request.POST.get('description')
            contact.save()
            messages.info(request, 'Note createrd successfully')
            return redirect('contact')
        else:
            messages.error(request, 'Note not createrd')
    context = {'form':form,}
    return render(request,'note/contact.html',context)

note/templates/note/allsubjects.html
{% extends 'main.html' %}

{% block content %}
<main class="create-room layout " >
  <div class="container">
    <div class="layout__box" style="top:50%;">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'note' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Browse Subjects</h3>
        </div>
      </div>

      <div class="topics-page layout__body">
        <form action="" method="GET" class="header__search">
          <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
              </path>
            </svg>
            <input name="q" placeholder="Search for topics" />
          </label>
        </form>

        <ul class="topics__list">
          <li>
            <a href="{% url 'subjects' %}" class="active">All <span>{{subjects.count}}</span></a>
          </li>
          {% for subject in subjects %}
          <li>
            <a href="{% url 'note' %}?q={{subject.name}}">{{ subject.name }} <span>{{subject.notes_set.all.count}}</span></a>
          </li>
          {% endfor %}

        </ul>
      </div>
    </div>
  </div>
</main>

{% endblock content %}

note/templates/note/browse_subject.html
<div class="topics">
  <div class="topics__header">
    <h2>Browse Subjects</h2>
  </div>
  <ul class="topics__list">
    <li>
      <a href="{% url 'note' %}" class="active"
        >All <span>{{note_count}}</span></a
      >
    </li>
    {% for subject in subjects %}
    <li>
      <a href="{% url 'note' %}?q={{subject.name}}"
        >{{subject.name}}<span>{{subject.notes_set.all.count}}</span></a
      >
    </li>
    {% endfor %}
  </ul>
  <a class="btn btn--link" href="{% url 'subjects' %}">
    More
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
      <!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
      <path
        d="M201.4 342.6c12.5 12.5 32.8 12.5 45.3 0l160-160c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L224 274.7 86.6 137.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3l160 160z"
      />
    </svg>
  </a>
</div>

note/templates/note/contact.html
{% extends 'main.html' %}

{% block content %}
<main class="update-account layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'note' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Contact Us</h3>
        </div>
      </div>
      <div class="layout__body">
        <form class="form" action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
            
          <div class="form__group">
            <label for="file chose">Name</label>
            {{form.name}}
          </div>
          <div class="form__group">
            <label for="file chose"> Choose Files</label>
            {{form.notesfile}}
          </div>
          <div class="form__group">
            <label for="description">* Description ( Must describe then content of file, otherwise don't approved the note.)</label>
            {{form.description}}
          </div>
          <div class="form__group">
            <label for="file chose"> Phone Number</label>
            {{form.phone}}
          </div>
            
          </div>


          <div class="form__action">
            <div style="padding:20px; display:flex; gap:1.2rem">
              <a class="btn btn--dark" href="{{request.META.HTTP_REFERER}}">Cancel</a>
            <button class="btn btn--main" type="submit">Submit</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  </div>
</main>
{% endblock content %}

note/templates/note/my_notes.html
{% extends 'main.html' %} {% block content %}

<main class="layout layout--3">
  <div class="container">
    <!-- Topics Start -->
    <div></div>

    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">
      <div class="roomList__header">
        <div>
          <h2>MY Notes</h2>
          <p>Notes available</p>
        </div>

        <a class="btn btn--main" href="{% url 'upload_notes' %}">
          <svg
            version="1.1"
            xmlns="http://www.w3.org/2000/svg"
            width="32"
            height="32"
            viewBox="0 0 32 32"
          >
            <title>add</title>
            <path
              d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
            ></path>
          </svg>
          Upload Note
        </a>
      </div>

      {% for note in notes%}
      <div class="roomListRoom">
        <div class="roomListRoom__header">
          <a
            href="{% url 'user-profile' note.user.username %}"
            class="roomListRoom__author"
          >
            <div class="avatar avatar--small">
              <img src="{{note.user.avatar.url}}" />
            </div>
            <span>@{{note.user.username}}</span>
          </a>
          <div class="roomListRoom__actions">
            <span class="roomListRoom__topic" style="font-size:15px">{{note.subject}}</span>
          </div>
        </div>
        <div class="roomListRoom__content">
          <a href="{{note.notesfile.url}}" download>{{note.notesfile}}</a>
          <br />
          <p>{{note.description}}</p>
        </div>
        <div class="roomListRoom__meta">
          <div class="roomListRoom__joined">
            <span style="font-size:14px">{{note.created|date:"d M , Y"}}</span>
          </div>
          
          
          <div>
            {% if note.status %}
            <span class="roomListRoom__topic" style="font-size:15px">Status : Approved</span>
            {% else %}
            <span class="roomListRoom__topic" style="font-size:15px">Status : Pending</span>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}

      <!-- <div class="center">
        <p style="padding: 10px; color:green;">{{page}} / {{roomdata.paginator.num_pages}} </p>
        <div class="pagination pagination1 pagination3 pagination4 pagination6">
          {% if roomdata.has_previous %}
          <a class="btn-page" href="?page=1" >First</a>
          <a class="btn-page" href="?page={{roomdata.previous_page_number}}" >Previous</a>
          {% endif %}
          {% for n in  totalpagelist%}
          <a class="btn-page" href="?page={{n}}">{{n}}</a>{% endfor %}
          {% if roomdata.has_next %}
          <a class="btn-page" href="?page={{roomdata.next_page_number}}">&raquo;</a>
          <a class="btn-page" href="?page={{lastpage}}">Last</a>
          {% endif %}
        </div>
      </div> -->
    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
    <div></div>
    <!-- Activities End -->
  </div>
</main>

{% endblock %}

note/templates/note/note.html
{% extends 'main.html' %} {% block content %}

<main class="layout layout--3">
  <div class="container">
    <!-- Topics Start -->
    {% include 'note/browse_subject.html' %}

    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">
      <div class="roomList__header">
        <div>
          <h2>Study Notes</h2>
          <p>{{note_count}} Notes available</p>
        </div>
        <form action="{% url 'note' %}" method="GET" class="header__search">
          <label>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
              <!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
              <path
                d="M416 208c0 45.9-14.9 88.3-40 122.7L502.6 457.4c12.5 12.5 12.5 32.8 0 45.3s-32.8 12.5-45.3 0L330.7 376c-34.4 25.2-76.8 40-122.7 40C93.1 416 0 322.9 0 208S93.1 0 208 0S416 93.1 416 208zM208 352a144 144 0 1 0 0-288 144 144 0 1 0 0 288z"
              />
            </svg>
            <input name="q" placeholder="Search for notes" />
          </label>
        </form>
        <a class="btn btn--main" href="{% url 'upload_notes' %}">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
            <!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
            <path
              d="M256 80c0-17.7-14.3-32-32-32s-32 14.3-32 32V224H48c-17.7 0-32 14.3-32 32s14.3 32 32 32H192V432c0 17.7 14.3 32 32 32s32-14.3 32-32V288H400c17.7 0 32-14.3 32-32s-14.3-32-32-32H256V80z"
            />
          </svg>
          Upload Note
        </a>
      </div>

      {% include 'note/note_component.html' %}

      <div class="center">
        <p style="padding: 10px; color: black; text-align:center;font-weight:500;font-size:20px">
          {{page}} / {{data.paginator.num_pages}}
        </p>
        <div class="pagination pagination1 pagination3 pagination4 pagination6">
          {% if data.has_previous %}
          <a class="btn-page" href="?page=1">First</a>
          <a class="btn-page" href="?page={{data.previous_page_number}}"
            >Previous</a
          >
          {% endif %} {% for n in totalpagelist%}
          <a class="btn-page" href="?page={{n}}">{{n}}</a>
          {% endfor %} {% if data.has_next %}
          <a class="btn-page" href="?page={{data.next_page_number}}">&raquo;</a>
          <a class="btn-page" href="?page={{lastpage}}">Last</a>
          {% endif %}
        </div>
      </div>
    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
    <div>
      <div class="roomList">
        {% for post in posts %}
          <div class="roomListRoom">
            
                <div class="roomList__header">
                  <a href="{% url "detail" post.slug %}" class="blogListRoom__author">
                    <div>
                      <span class="blog-title">{{post.title}}</span>
                      {{post.content|safe|truncatechars:300}} read more
                      <div class="blogListRoom__actions">
                         Publised : {{post.created|date:"d M"}}
                      </div>
                     </div>
                  </a>
                  
                </div>
             
          </div>
          {% endfor %}
        </div>
    </div>
    <!-- Activities End -->
  </div>
</main>

{% endblock %}

note/templates/note/note_component.html
{% for note in data%} {% if note.status %}
<div class="roomListRoom">
  <div class="roomListRoom__header">
    <a
      href="{% url 'user-profile' note.user.username %}"
      class="roomListRoom__author"
    >
      <div class="avatar avatar--small">
        <img src="{{note.user.avatar.url}}" />
      </div>
      <span>@{{note.user.username}}</span>
    </a>
    <div class="roomListRoom__actions">
      <span>{{note.subject}}</span>
    </div>
  </div>
  <div class="roomListRoom__content">
    {% comment %} <a href="{{note.notesfile.url}}" download>{{note.notesfile}}</a> <br /> {% endcomment %}
    <p>{{note.description}}</p>
  </div>
  <div class="roomListRoom__meta">
    <div class="roomListRoom__joined">
      <span>{{note.created|timesince}} ago</span>
    </div>
    <div>
        <button class="btn btn--dark" onclick="location.href='{% url 'download_note' note.id %}'"><a style="color:white" href="{{note.notesfile.url}}" download>Download</a></button>
    </div>
    <p class="roomListRoom__topic">Total Downloads : {{note.downloads}}</p>
  </div>
</div>

{% endif %} {% endfor %}

note/templates/note/sucess.html
{% extends 'main.html' %} {% load static %} {% block content %}
<main class="layout layout--3">
  <div class="container">
    <div></div>
    <div class="">
      <img src="{% static 'assets/bg-back/success.gif' %}" alt="" />
      <div style="text-align:center; margin-top:2%">
        File Downloaded Successfully <a class="btn btn--dark" href="{% url 'note' %}">Back to Home</a>
      </div>
    </div>
    <div></div>
  </div>
</main>
{% endblock content %}

note/templates/note/upload_note.html
{% extends 'main.html' %}

{% block content %}
<main class="update-account layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'note' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Upload yours Notes</h3>
        </div>
      </div>
      <div class="layout__body">
        <form class="form" action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}

          <div class="form__group">
            <label for="Branch">Branch</label>
            {{form.branch}}
          </div>
          <div class="form__group">
            <label for="room_topic">Subject</label>
            <input
              required
              type="text"
              value="{{note.allsubject.name}}"
              name="subject"
              list="topic-list"
            />
            <datalist id="topic-list">
              <select id="room_topic">
                {% for subject in subjects %}
                <option value="{{subject.name}}">{{subject.name}}</option>
                {% endfor %}
              </select>
            </datalist>
          </div>
          <div class="form__group">
            <label for="file chose"> Choose Files</label>
            {{form.notesfile}}
          </div>
          <div class="form__group">
            <label for="file type"> File Type</label>
            {{form.filetype}}
          </div>
          <div class="form__group">
            <label for="description">* Description ( Must describe then content of file, otherwise don't approved the note.)</label>
            {{form.description}}
          </div>
          
            
          </div>


          <div class="form__action">
            <div style="padding:20px; display:flex; gap:1.2rem">
              <a class="btn btn--dark" href="{{request.META.HTTP_REFERER}}">Cancel</a>
            <button class="btn btn--main" type="submit">Upload</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  </div>
</main>
{% endblock content %}