base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerPage, name="register"),
    

    #path('', views.home, name="home"),
   
    path('profile/<str:username>/', views.userProfile, name="user-profile"),
    path('update-user/', views.updateUser, name="update-user"),

    path('', views.rooms, name="rooms"),
    path('room/<str:pk>/', views.room, name="room"),
    path('create-room/', views.createRoom, name="create-room"),
    path('update-room/<str:pk>/', views.updateRoom, name="update-room"),
    path('delete-room/<str:pk>/', views.deleteRoom, name="delete-room"),
    path('delete-message/<str:pk>/', views.deleteMessage, name="delete-message"),

    path('topics/', views.topicsPage, name="topics"),
    path('activity/', views.activityPage, name="activity"),
]

products/urls.py
from django.urls import path
from . import views
from .views import CreateStripeCheckoutSessionView,CancelView, SuccessView
from .views import StripeWebhookView


app_name = "products"

urlpatterns = [

    path("", views.ProductListView, name="product-list"),
    path("<int:pk>/", views.ProductDetailView, name="product-detail"),
    path(
        "create-checkout-session/<int:pk>/",
        CreateStripeCheckoutSessionView.as_view(),
        name="create-checkout-session",
    ),
    path("webhooks/stripe/", StripeWebhookView.as_view(), name="stripe-webhook"),
    path("success/", views.SuccessView, name="success"),
    path("cancel/", views.CancelView, name="cancel"),
]

shareMeNote/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rooms/', include('base.urls')),
     path('', include('note.urls')),
    path('blog/', include('blog.urls')),
    path("products/", include("products.urls")),
    path('social-auth/', include('social_django.urls', namespace='social')), # <--
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from base.models import User
from django.template.defaultfilters import slugify
from django.utils.translation import gettext_lazy as _

def get_image_filename(instance, filename):
    name = instance.name
    slug = slugify(name)
    return f"products/{slug}-{filename}"

class ProductTag(models.Model):
    name = models.CharField(
        max_length=100, help_text=_("Designates the name of the tag.")
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200)
    tags = models.ManyToManyField(ProductTag, blank=True)
    desc = models.TextField(_("Description"), blank=True)
    thumbnail = models.ImageField(upload_to=get_image_filename, blank=True)
    url = models.URLField()
    quantity = models.IntegerField(default=1)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created_at",)

    def __str__(self):
        return self.name

class Price(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(decimal_places=2, max_digits=10)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.product.name} {self.price}"


class PaymentHistory(models.Model):
    PENDING = "P"
    COMPLETED = "C"
    FAILED = "F"

    STATUS_CHOICES = (
        (PENDING, _("pending")),
        (COMPLETED, _("completed")),
        (FAILED, _("failed")),
    )

    email = models.EmailField()
    
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    payment_status = models.CharField(
        max_length=1, choices=STATUS_CHOICES, default=PENDING
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.name

products/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render,redirect
from django.views import View
from django.core.mail import send_mail
from .models import PaymentHistory 
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
import stripe
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Price, Product

stripe.api_key = settings.STRIPE_SECRET_KEY

class CreateStripeCheckoutSessionView(LoginRequiredMixin,View):
    """
    Create a checkout session and redirect the user to Stripe's checkout page

    need to run this command on cmd : listen --forward-to localhost:8000/products/webhooks/stripe/
    """
    
    LOGIN_URL = 'login'

    def post(self, request, *args, **kwargs):
        price = Price.objects.get(id=self.kwargs["pk"])

        checkout_session = stripe.checkout.Session.create(
            payment_method_types=["card"],
            line_items=[
                {
                    "price_data": {
                        "currency": "usd",
                        "unit_amount": int(price.price) * 100,
                        "product_data": {
                            "name": price.product.name,
                            "description": price.product.desc,
                            "images": [
                                f"{settings.BACKEND_DOMAIN}/{price.product.thumbnail}"
                            ],
                        },
                    },
                    "quantity": price.product.quantity,
                }
            ],
            metadata={"product_id": price.product.id},
            mode="payment",
            success_url=settings.PAYMENT_SUCCESS_URL,
            cancel_url=settings.PAYMENT_CANCEL_URL,
        )
        return redirect(checkout_session.url)
    

@method_decorator(csrf_exempt, name="dispatch")
class StripeWebhookView(View):
    """
    Stripe webhook view to handle checkout session completed event.
    """

    def post(self, request, format=None):
        payload = request.body
        endpoint_secret = settings.STRIPE_WEBHOOK_SECRET
        sig_header = request.META["HTTP_STRIPE_SIGNATURE"]
        event = None

        try:
            event = stripe.Webhook.construct_event(payload, sig_header, endpoint_secret)
        except ValueError as e:
            # Invalid payload
            return HttpResponse(status=400)
        except stripe.error.SignatureVerificationError as e:
            # Invalid signature
            return HttpResponse(status=400)

        if event["type"] == "checkout.session.completed":
            print("Payment successful")
            session = event["data"]["object"]
            customer_email = session["customer_details"]["email"]
            product_id = session["metadata"]["product_id"]
            product = get_object_or_404(Product, id=product_id)

            send_mail(
                subject="Here is your product",
                message=f"Thanks for your purchase. The URL is: {product.url}",
                recipient_list=[customer_email],
                from_email="user@gmail.com",
            )

            PaymentHistory.objects.create(
                email=customer_email, product=product, payment_status="C"
            ) # Add this
        else :
            PaymentHistory.objects.create(
                email=customer_email, product=product, payment_status="F"
            ) # Add this
        # Can handle other events here.

        return HttpResponse(status=200)
    

def ProductListView(request):
     products = Product.objects.all()
     context = {'products':products}
     return render(request,'products/product_list.html', context)


def ProductDetailView(request,pk):

    product = get_object_or_404(Product, pk=pk)
    prices = Price.objects.filter(product=product)

    context = {
        'product': product,
        'prices': prices
    }
    return render(request,'products/product_detail.html', context)

def SuccessView(request):
    return render(request,"products/success.html")

def CancelView(request):
    return render(request,"products/cancel.html")

products/templates/products/cancel.html
{% extends "main.html" %} 
{% block title %} Cancel {% endblock title%} 
{% block content %}
<div style="margin-top:8%">
    <div class="alert alert-info" role="alert">
        Forgot to add something to your cart?
        <a
            href="{% url 'products:product-list' %}"
            >Go to Products</a
          >
      </div>
</div>
{% endblock content %}

products/templates/products/product_detail.html
{% extends 'main.html' %}
{% block title %} Buy Product {% endblock title%} 
{% block content %}
<div style="margin-top:8%;">
  <div class="card-deck" style=" box-shadow: 7px 7px 25px grey; width: 60%;  margin: 0 auto; display: flex; flex-direction: column; justify-content: center; align-items: center; padding: 30px 0 30px 0;border-radius: 1rem;">
    {% for price in prices %}
    <div class="card" style="width: 60%; margin: 0 auto; display: flex; flex-direction: column; justify-content: center; align-items: center;">
      <img
        class="card-img-top"
        src="{{product.thumbnail.url}}"
        alt="Card image cap"
        style="width: 400px; height: 100%; border-radius: 1rem;"
      />
      <div class="card-body" style="display: flex; flex-direction: column; justify-content: center; align-items: center;">
        <h5 class="card-title" style="font-size: 200%;">{{product.name}}</h5>
        <p class="card-text" style="font-size:larger; text-align: justify;">{{product.desc}}</p>
        <div class="card-text" style="width: 100%;">
          <h5 class="card-text" style="font-size: 300%; display: flex; align-items: center; justify-content: center;">${{ price.price }}</h5>
          
          <form
          action="{% url 'products:create-checkout-session' price.id %}"
          method="POST"
          >
            {% csrf_token %}
            <button type="submit"  class="btn btn--dark"
            style="width: 100%; display: flex; justify-content: center;">Checkout</button>
          </form>
          
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}

products/templates/products/product_list.html
{% extends 'main.html' %} {% block title %} Products {% endblock title%} 
{%block content %} {% for product in products %}

<main class="layout--3 layout">
  <div class="container">
    <div></div>
    <div class="roomList">
      <div class="roomListRoom">
        <div class="blogListRoom__header">
          <a
            href="{% url 'products:product-detail' product.id %}"
            class="blogListRoom__author"
          >
            <div class="blog-img blog--small">
              <img src="{{product.thumbnail.url}}" />
            </div>
            <div style="text-align: justify;">
              <span class="blog-title">{{product.name}}</span>
              {{product.desc|safe|truncatechars:200}} <more style="color: gray;">read more</more> 
            </div>
          </a>
        </div>

        <div class="" style="margin-top:2%">

          <a
              href="{% url 'products:product-detail' product.id %}"
              class="btn btn--dark"
              style="width: 100%; display: flex; justify-content: center;"
              >View Detail</a
            >
        </div>
      </div>
    </div>
    <div></div>
  </div>
</main>

{% endfor %} {%endblock content%}

products/templates/products/success.html
{% extends 'main.html' %} {% load static %} {% block content %}
<main class="layout layout--3">
  <div class="container">
    <div></div>
    <div class="">
      <img src="{% static 'assets/bg-back/success.gif' %}" alt="" />
      <div style="text-align:center; margin-top:2%">
        <div>
          <p>Check your Mail </p>
        </div>
        Payment Successfully <a class="btn btn--dark" href="{% url 'products:product-list' %}">Go to Products</a>
      </div>
    </div>
    <div></div>
  </div>
</main>
{% endblock content %}


<a href="{% url 'products:product-list' %}">Go to Products</a>